/*
   Generated by EX4-TO-MQ4 decompiler LITE V4.0.427.1 [-]
   Website: https://purebeam.biz
   E-mail : purebeam@gmail.com
*/
// Modify by LyaSer

#property copyright "Fxsourcecode © 2012, Forex Source Code Inc."
#property link      "http://www.forexsourcecode.net"

/*
#import "FGT1.dll"
   int func1(int a0, int a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8, string a9, int a10, int& a11[], int& a12[]);
   int func2(string a0, int a1, int& a2[], int& a3[]);
   void func3();
#import
*/

extern bool ShowTradeComment = TRUE;
extern double Lots = 0.01;
extern double MultiLotsFactor = 1.6;
extern double StepLots = 15.0;
extern double TakeProfit = 23.0;
extern bool UseTrailing = FALSE;
extern double TrailStart = 38.0;
extern double TrailStop = 18.0;
extern int MaxOpenOrders = 15;
extern bool SafeEquityStopOut = FALSE;
extern double SafeEquityRisk = 0.5;
extern double Slippage = 3.0;
extern int xMagicNumber = 2024536;
extern string TradeComment = "FxGridTraderEA";
extern int TradingType = 0;
   // 0 - Open Long and Short positins use magic number = MagicNumber (Long or Short position configuring in common options on expert property window)
   // 1 - Open only Long position use magic number - MagicNumber
   // 2 - Open only Short position use magic number - MagicNumber
   // 3 - Open Long and Short positions use magic for BUY - MagicNumber and magic for SELL - AdvMagicNumber
extern int AdvMagicNumber = 2024537;
bool CloseAllOrdersBeforeStart = FALSE;
double StopTradeHour = 48.0;
double StopLoss = 500.0;
double LotExp = 0.0;
bool gi_212 = TRUE;
bool gi_216 = FALSE;
int TypeCalculationLots = 1;
double newProffit[]={0,0};
double orderPrice[]={0,0};
double LastBuyOrderPrice[]={0,0};
double LastSellOrderPrice[]={0,0};
//double spread;
int oldTime[] = {0,0};
int CurrentTime[]={0,0};
int gi_300[] = {0,0};
double opLot[]={0,0};
int oCount[]={0,0};
bool trade[]={false,false};
//double gd_320 = 0.0;
bool gi_332[] = {FALSE,false};
bool gi_336[] = {FALSE,false};
bool modify[] = {FALSE,false};
int TimeCloseOrderBUY = 0;
int TimeCloseOrderSELL = 0;
double maxAccEqu;
double oldAccEqu;
string SafeEquityStr = "OFF";
string sTraiding = "LIVE";
string stErr = "";
bool initErr = TRUE;
//int AccNum = 0;
int xPoints;

int init() {
   // func3();
   if (Digits == 2 || Digits == 4) xPoints = 1;
   else xPoints = 10;
//   AccNum = AccountNumber();
//   spread = MarketInfo(Symbol(), MODE_SPREAD) * Point * xPoints;
   switch (MarketInfo(Symbol(), MODE_MINLOT)) {
   case 0.001:
      LotExp = 3;
      break;
   case 0.01:
      LotExp = 2;
      break;
   case 0.1:
      LotExp = 1;
      break;
   case 1.0:
      LotExp = 0;
   }
   if (SafeEquityStopOut) SafeEquityStr = "ON";
   if (IsDemo()) sTraiding = "DEMO";
   /*
   if (StringLen(CLICKBANKID) < 5) {
      Print("FGT ERROR :: Enter a valid CLICKBANK ID!!!");
      Alert("FGT | ERROR :: ", " Please INSERT a valid CLICKBANK ID.");
      gs_396 = "Please INSERT a valid CLICKBANK ID.";
   }
   */
   if (Period() != PERIOD_M1) {
      Print("FGT ERROR :: Invalid Timeframe, Please switch to M1.");
      Alert("FGT ERROR :: ", " Invalid Timeframe, Please switch to M1.");
      stErr = "Invalid Timeframe. FGT works on M1";
      initErr = FALSE;
   }
   if (IsDllsAllowed() == FALSE) {
      Print("FGT ERROR :: DLL call is not allowed. Experts cannot run.");
      Alert("FGT ERROR :: ", " Please Allow DLL call.");
      stErr = "FGT ERROR :: Please Allow DLL call.";
      initErr = FALSE;
      return (0);
   }
   return (0);
}

int deinit() {
   Comment("");
   if (ObjectFind("BG") >= 0) ObjectDelete("BG");
   if (ObjectFind("BG1") >= 0) ObjectDelete("BG1");
   if (ObjectFind("BG2") >= 0) ObjectDelete("BG2");
   if (ObjectFind("BG3") >= 0) ObjectDelete("BG3");
   if (ObjectFind("BG4") >= 0) ObjectDelete("BG4");
   if (ObjectFind("BG5") >= 0) ObjectDelete("BG5");
   if (ObjectFind("NAME") >= 0) ObjectDelete("NAME");
   return (0);
}

int start() {
   int ret;
   ret = Processing(0);
   if (ret>0) return(ret);
   if (TradingType==3) ret = ret && Processing(1);
   return(ret);
}

int Processing(int tt){
   //int lia_0[1];
   //int lia_4[1];
   int ticket;
   bool gi_328 = FALSE;
   double buyLots;
   double sellLots;
   double bClose2;
   double bClose1;
   double summLots = 0;
   double  prf;
   int i = 0;
   int mag;
   bool doOpen;
   /*
   int li_8 = func2(CLICKBANKID, gi_416, lia_0, lia_4);
   if (li_8 != 0) {
      gs_388 = lia_0[0];
      gs_396 = f0_12(lia_4[0]);
      f0_13();
      return (-1);
   }
   */
   
   switch (TradingType){
     case  3: if (tt==1) mag=AdvMagicNumber; else mag=xMagicNumber; break;
     default: mag=xMagicNumber;
   }
   Print("Magic number:",mag);
   if (UseTrailing) Trail(TrailStart, TrailStop, orderPrice[tt], mag);
   if (CloseAllOrdersBeforeStart) {
      if (TimeCurrent() >= CurrentTime[tt]) {
         CloseAllOrders(mag);
         Print("Closed All Trades Due To Server TimeOut");
      }
   }
   if (oldTime[tt] == Time[0]) return (0);
   oldTime[tt] = Time[0];
   prf = CalcProffit(mag);
   if (SafeEquityStopOut) 
     if (prf < 0.0 && MathAbs(prf) > SafeEquityRisk / 100.0 * GetAccountEquity(mag)) {
        CloseAllOrders(mag);
        modify[tt] = FALSE;
        Print("Closed All due to EQUITY STOP-OUT");
     }
   oCount[tt] = GetCountOrders(mag);
   if (oCount[tt] == 0) trade[tt] = FALSE;
   for (i = OrdersTotal() - 1; i >= 0; i--) {
      OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != mag) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == mag) {
         if (OrderType() == OP_BUY) {
            gi_332[tt] = TRUE;
            gi_336[tt] = FALSE;
            buyLots = OrderLots();
            break;
         }
      }
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == mag) {
         if (OrderType() == OP_SELL) {
            gi_332[tt] = FALSE;
            gi_336[tt] = TRUE;
            sellLots = OrderLots();
            break;
         }
      }
   }
   gi_328 = FALSE;
   if (oCount[tt] > 0 && oCount[tt] <= MaxOpenOrders) {
      RefreshRates();
      LastBuyOrderPrice[tt] = GetPriceLastOrder(OP_BUY, mag);
      LastSellOrderPrice[tt] = GetPriceLastOrder(OP_SELL, mag);
      gi_328 = func1(gi_332[tt], gi_336[tt], Bid, Ask, LastBuyOrderPrice[tt], LastSellOrderPrice[tt], Point, StepLots, xPoints);
      stErr = ReturnErrorMsg(3);
      // if (StringLen(CLICKBANKID) < 5) gs_396 = f0_12(5);
   }
   if (oCount[tt] < 1) {
      gi_336[tt] = FALSE;
      gi_332[tt] = FALSE;
      gi_328 = TRUE;
   }
   if (gi_328) {
      LastBuyOrderPrice[tt] = GetPriceLastOrder(OP_BUY, mag);
      LastSellOrderPrice[tt] = GetPriceLastOrder(OP_SELL, mag);
      if (gi_336[tt]) {
         if (gi_216) {
            CloseAllOrdersBS(false, true, mag);
            opLot[tt] = NormalizeDouble(MultiLotsFactor * sellLots, LotExp);
         } else opLot[tt] = CalcLot(OP_SELL, mag, tt);
         if (gi_212) {
            gi_300[tt] = oCount[tt];
            if (opLot[tt] > 0.0) {
               RefreshRates();
               if (TradingType==3 && tt==0) doOpen=false;
                  else
                    if (TradingType==3 && tt==1) doOpen=true;
                      else
                        if (TradingType==1) doOpen=false; else doOpen=true;
               if (doOpen)
                  ticket = OpenOrder(OP_SELL, opLot[tt], Slippage, 0, 0, TradeComment + "-" + gi_300[tt], mag, 0, HotPink);
                  else ticket = -1;
               if (ticket < 0) {
                  Print("Error: ", GetLastError());
                  return (0);
               }
               LastSellOrderPrice[tt] = GetPriceLastOrder(OP_SELL, mag);
               gi_328 = FALSE;
               modify[tt] = TRUE;
            }
         }
      } else {
         if (gi_332[tt]) {
            if (gi_216) {
               CloseAllOrdersBS(true, false, mag);
               opLot[tt] = NormalizeDouble(MultiLotsFactor * buyLots, LotExp);
            } else opLot[tt] = CalcLot(OP_BUY, mag, tt);
            if (gi_212) {
               gi_300[tt] = oCount[tt];
               if (opLot[tt] > 0.0) {
                  if (TradingType==3 && tt==0) doOpen=true;
                     else
                       if (TradingType==3 && tt==1) doOpen=false;
                         else
                           if (TradingType==2) doOpen=false; else doOpen=true;
                  if (doOpen)
                    ticket = OpenOrder(OP_BUY, opLot[tt], Slippage, 0, 0, TradeComment + "-" + gi_300[tt], mag, 0, Lime);
                    else ticket = -1;
                  if (ticket < 0) {
                     Print("Error: ", GetLastError());
                     return (0);
                  }
                  LastBuyOrderPrice[tt] = GetPriceLastOrder(OP_BUY, mag);
                  gi_328 = FALSE;
                  modify[tt] = TRUE;
               }
            }
         }
      }
   }
   if (gi_328 && oCount[tt] < 1) {
      bClose2 = iClose(Symbol(), 0, 2);
      bClose1 = iClose(Symbol(), 0, 1);
      if ((!gi_336[tt]) && !gi_332[tt]) {
         gi_300[tt] = oCount[tt];
         if (bClose2 > bClose1) {
            opLot[tt] = CalcLot(OP_SELL, mag, tt);
            if (opLot[tt] > 0.0) {
               if (TradingType==3 && tt==0) doOpen=false;
                  else
                    if (TradingType==3 && tt==1) doOpen=true;
                      else
                        if (TradingType==1) doOpen=false; else doOpen=true;
               if (doOpen)
                  ticket = OpenOrder(OP_SELL, opLot[tt], Slippage, 0, 0, TradeComment + " " + mag + "-" + gi_300[tt], mag, 0, HotPink);
                  else ticket = -1;
               if (ticket < 0) {
                  Print(opLot[tt], "Error: ", GetLastError());
                  return (0);
               }
               LastBuyOrderPrice[tt] = GetPriceLastOrder(OP_BUY, mag);
               modify[tt] = TRUE;
            }
         } else {
            opLot[tt] = CalcLot(OP_BUY, mag, tt);
            if (opLot[tt] > 0.0) {
               if (TradingType==3 && tt==0) doOpen=true;
                  else
                    if (TradingType==3 && tt==1) doOpen=false;
                      else
                        if (TradingType==2) doOpen=false; else doOpen=true;
               if (doOpen)
                 ticket = OpenOrder(OP_BUY, opLot[tt], Slippage, 0, 0, TradeComment + " " + mag + "-" + gi_300[tt], mag, 0, Lime);
                 else ticket = -1;
               if (ticket < 0) {
                  Print(opLot[tt], "Error: ", GetLastError());
                  return (0);
               }
               LastSellOrderPrice[tt] = GetPriceLastOrder(OP_SELL, mag);
               modify[tt] = TRUE;
            }
         }
      }
      if (ticket > 0) CurrentTime[tt] = TimeCurrent() + 60.0 * (60.0 * StopTradeHour);
      gi_328 = FALSE;
   }
   oCount[tt] = GetCountOrders(mag);
   orderPrice[tt] = 0;
   for (i = OrdersTotal() - 1; i >= 0; i--) {
      OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != mag) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == mag) {
         if (OrderType() == OP_BUY || OrderType() == OP_SELL) {
            orderPrice[tt] += OrderOpenPrice() * OrderLots();
            summLots += OrderLots();
         }
      }
   }
   if (oCount[tt] > 0) orderPrice[tt] = NormalizeDouble(orderPrice[tt] / summLots, Digits);
   if (modify[tt]) {
      for (i = OrdersTotal() - 1; i >= 0; i--) {
         OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
         if (OrderSymbol() != Symbol() || OrderMagicNumber() != mag) continue;
         if (OrderSymbol() == Symbol() && OrderMagicNumber() == mag) {
            if (OrderType() == OP_BUY) {
               newProffit[tt] = orderPrice[tt] + TakeProfit * Point * xPoints;
//               gd_320 = orderPrice[tt] - StopLoss * Point * xPoints;
               trade[tt] = TRUE;
            }
         }
         if (OrderSymbol() == Symbol() && OrderMagicNumber() == mag) {
            if (OrderType() == OP_SELL) {
               newProffit[tt] = orderPrice[tt] - TakeProfit * Point * xPoints;
//               gd_320 = orderPrice[tt] + StopLoss * Point * xPoints;
               trade[tt] = TRUE;
            }
         }
      }
   }
   if (modify[tt]) {
      if (trade[tt] == TRUE) {
         for (i = OrdersTotal() - 1; i >= 0; i--) {
            OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
            if (OrderSymbol() != Symbol() || OrderMagicNumber() != mag) continue;
            if (OrderSymbol() == Symbol() && OrderMagicNumber() == mag) OrderModify(OrderTicket(), orderPrice[tt], OrderStopLoss(), newProffit[tt], 0, Yellow);
            modify[tt] = FALSE;
         }
      }
   }
   ViewComment();
   return (0);
}

void ViewComment() {
   if (ShowTradeComment) {
      if (ObjectFind("BG") < 0) {
         ObjectCreate("BG", OBJ_LABEL, 0, 0, 0);
         ObjectSetText("BG", "g", 195, "Webdings", Orange);
         ObjectSet("BG", OBJPROP_CORNER, 0);
         ObjectSet("BG", OBJPROP_BACK, TRUE);
         ObjectSet("BG", OBJPROP_XDISTANCE, 0);
         ObjectSet("BG", OBJPROP_YDISTANCE, 15);
      }
      if (ObjectFind("BG1") < 0) {
         ObjectCreate("BG1", OBJ_LABEL, 0, 0, 0);
         ObjectSetText("BG1", "g", 195, "Webdings", DimGray);
         ObjectSet("BG1", OBJPROP_BACK, FALSE);
         ObjectSet("BG1", OBJPROP_XDISTANCE, 0);
         ObjectSet("BG1", OBJPROP_YDISTANCE, 42);
      }
      if (ObjectFind("BG2") < 0) {
         ObjectCreate("BG2", OBJ_LABEL, 0, 0, 0);
         ObjectSetText("BG2", "g", 195, "Webdings", DimGray);
         ObjectSet("BG2", OBJPROP_CORNER, 0);
         ObjectSet("BG2", OBJPROP_BACK, TRUE);
         ObjectSet("BG2", OBJPROP_XDISTANCE, 0);
         ObjectSet("BG2", OBJPROP_YDISTANCE, 42);
      }
      if (ObjectFind("NAME") < 0) {
         ObjectCreate("NAME", OBJ_LABEL, 0, 0, 0);
         ObjectSetText("NAME", "FOREX GRID TRADER EA - " + Symbol(), 9, "Arial Bold", White);
         ObjectSet("NAME", OBJPROP_CORNER, 0);
         ObjectSet("NAME", OBJPROP_BACK, FALSE);
         ObjectSet("NAME", OBJPROP_XDISTANCE, 5);
         ObjectSet("NAME", OBJPROP_YDISTANCE, 23);
      }
      if (ObjectFind("BG3") < 0) {
         ObjectCreate("BG3", OBJ_LABEL, 0, 0, 0);
         ObjectSetText("BG3", "g", 95, "Webdings", DimGray);
         ObjectSet("BG3", OBJPROP_CORNER, 0);
         ObjectSet("BG3", OBJPROP_BACK, TRUE);
         ObjectSet("BG3", OBJPROP_XDISTANCE, 0);
         ObjectSet("BG3", OBJPROP_YDISTANCE, 110);
      }
      if (ObjectFind("BG5") < 0) {
         ObjectCreate("BG5", OBJ_LABEL, 0, 0, 0);
         ObjectSetText("BG5", "g", 195, "Webdings", DimGray);
         ObjectSet("BG5", OBJPROP_CORNER, 0);
         ObjectSet("BG5", OBJPROP_BACK, FALSE);
         ObjectSet("BG5", OBJPROP_XDISTANCE, 0);
         ObjectSet("BG5", OBJPROP_YDISTANCE, 110);
      }
      GetAccountInfo();
   }
}

double NormalizePrice(double price) {
   return (NormalizeDouble(price, Digits));
}

int CloseAllOrdersBS(bool onlyBUY = TRUE, bool onlySELL = TRUE, int magic = 0) {
   int ret = 0;
   for (int i = OrdersTotal() - 1; i >= 0; i--) {
      if (OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
         if (OrderSymbol() == Symbol() && OrderMagicNumber() == magic) {
            if (OrderType() == OP_BUY && onlyBUY) {
               RefreshRates();
               if (!IsTradeContextBusy()) {
                  if (!OrderClose(OrderTicket(), OrderLots(), NormalizePrice(Bid), 5, CLR_NONE)) {
                     Print("Error close BUY " + OrderTicket());
                     ret = -1;
                  }
               } else {
                  if (TimeCloseOrderBUY == iTime(NULL, 0, 0)) return (-2);
                  TimeCloseOrderBUY = iTime(NULL, 0, 0);
                  Print("Need close BUY " + OrderTicket() + ". Trade Context Busy");
                  return (-2);
               }
            }
            if (OrderType() == OP_SELL && onlySELL) {
               RefreshRates();
               if (!IsTradeContextBusy()) {
                  if (!(!OrderClose(OrderTicket(), OrderLots(), NormalizePrice(Ask), 5, CLR_NONE))) continue;
                  Print("Error Closing SELL Trade : " + OrderTicket());
                  ret = -1;
                  continue;
               }
               if (TimeCloseOrderSELL == iTime(NULL, 0, 0)) return (-2);
               TimeCloseOrderSELL = iTime(NULL, 0, 0);
               Print("Need to close SELL trade : " + OrderTicket() + ". Trade Context Busy");
               return (-2);
            }
         }
      }
   }
   return (ret);
}

double CalcLot(int cmd, int magic, int tt) {
   double lot;
   int ocTime;
   switch (TypeCalculationLots) {
   case 0:
      lot = Lots;
      break;
   case 1:
      lot = NormalizeDouble(Lots * MathPow(MultiLotsFactor, gi_300[tt]), LotExp);
      break;
   case 2:
      ocTime = 0;
      lot = Lots;
      for (int i = OrdersHistoryTotal() - 1; i >= 0; i--) {
         if (!(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))) return (-3);
         if (OrderSymbol() == Symbol() && OrderMagicNumber() == magic) {
            if (ocTime < OrderCloseTime()) {
               ocTime = OrderCloseTime();
               if (OrderProfit() < 0.0) {
                  lot = NormalizeDouble(OrderLots() * MultiLotsFactor, LotExp);
                  continue;
               }
               lot = Lots;
               continue;
               return (-3);
            }
         }
      }
   }
   if (AccountFreeMarginCheck(Symbol(), cmd, lot) <= 0.0) return (-1);
   if (GetLastError() == 134/* NOT_ENOUGH_MONEY */) return (-2);
   return (lot);
}

int GetCountOrders(int magic) {
   int count = 0;
   for (int i = OrdersTotal() - 1; i >= 0; i--) {
      OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != magic) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == magic)
         if (OrderType() == OP_SELL || OrderType() == OP_BUY) count++;
   }
   return (count);
}

void CloseAllOrders(int magic) {
   for (int i = OrdersTotal() - 1; i >= 0; i--) {
      OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() == Symbol()) {
         if (OrderSymbol() == Symbol() && OrderMagicNumber() == magic) {
            if (OrderType() == OP_BUY) OrderClose(OrderTicket(), OrderLots(), Bid, Slippage, Blue);
            if (OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), Ask, Slippage, Red);
         }
         Sleep(1000);
      }
   }
}

int OpenOrder(int cmd, double lot, int SP, int SL, int PF, string OC, int OMagic, int OE, color Color) {
   int ticket = 0;
   int errCode = 0;
   int i = 0;
   int TryCount = 100;
   switch (cmd) {
   case OP_BUY:
      for (i = 0; i < TryCount; i++) {
         RefreshRates();
         ticket = OrderSend(Symbol(), cmd, lot, Ask, SP, GetStopProffit(Bid, -SL), GetStopProffit(Ask, PF), OC, OMagic, OE, Color);
         errCode = GetLastError();
         if (errCode == 0/* NO_ERROR */) break;
         if (!((errCode == 4/* SERVER_BUSY */ || errCode == 137/* BROKER_BUSY */ || errCode == 146/* TRADE_CONTEXT_BUSY */ || errCode == 136/* OFF_QUOTES */))) break;
         Sleep(5000);
      }
      break;
   case OP_SELL:
      for (i = 0; i < TryCount; i++) {
         RefreshRates();
         ticket = OrderSend(Symbol(), cmd, lot, Bid, SP, GetStopProffit(Ask, SL), GetStopProffit(Bid, -PF), OC, OMagic, OE, Color);
         errCode = GetLastError();
         if (errCode == 0/* NO_ERROR */) break;
         if (!((errCode == 4/* SERVER_BUSY */ || errCode == 137/* BROKER_BUSY */ || errCode == 146/* TRADE_CONTEXT_BUSY */ || errCode == 136/* OFF_QUOTES */))) break;
         Sleep(5000);
      }
   }
   return (ticket);
}

double GetStopProffit(double price, int pnt) {
   if (pnt == 0) return (0);
   return (price + pnt * Point * xPoints);
}

double CalcProffit(int magic) {
   double prf = 0;
   for (int i = OrdersTotal() - 1; i >= 0; i--) {
      OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != magic) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == magic)
         if (OrderType() == OP_BUY || OrderType() == OP_SELL) prf += OrderProfit();
   }
   return (prf);
}

void Trail(int Start, int End, double price, int magic) {
   int li_16;
   double SL;
   double ld_28;
   if (End != 0) {
      for (int i = OrdersTotal() - 1; i >= 0; i--) {
         if (OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
            if (OrderSymbol() != Symbol() || OrderMagicNumber() != magic) continue;
            if (OrderSymbol() == Symbol() || OrderMagicNumber() == magic) {
               if (OrderType() == OP_BUY) {
                  li_16 = NormalizeDouble((Bid - price) / Point / xPoints, 0);
                  if (li_16 < Start) continue;
                  SL = OrderStopLoss();
                  ld_28 = Bid - End * Point * xPoints;
                  if (SL == 0.0 || (SL != 0.0 && ld_28 > SL)) OrderModify(OrderTicket(), price, ld_28, OrderTakeProfit(), 0, Aqua);
               }
               if (OrderType() == OP_SELL) {
                  li_16 = NormalizeDouble((price - Ask) / Point / xPoints, 0);
                  if (li_16 < Start) continue;
                  SL = OrderStopLoss();
                  ld_28 = Ask + End * Point * xPoints;
                  if (SL == 0.0 || (SL != 0.0 && ld_28 < SL)) OrderModify(OrderTicket(), price, ld_28, OrderTakeProfit(), 0, Red);
               }
            }
            Sleep(1000);
         }
      }
   }
}

double GetAccountEquity(int magic) {
   if (GetCountOrders(magic) == 0) maxAccEqu = AccountEquity();
   if (maxAccEqu < oldAccEqu) maxAccEqu = oldAccEqu;
                   else maxAccEqu = AccountEquity();
   oldAccEqu = AccountEquity();
   return (maxAccEqu);
}

double GetPriceLastOrder(int tOper, int magic) {
   double OPrice;
   int ticket;
//   double oldOrderPrice = 0;
   int oldTicket = 0;
   for (int i = OrdersTotal() - 1; i >= 0; i--) {
      OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
      if (OrderSymbol() != Symbol() || OrderMagicNumber() != magic) continue;
      if (OrderSymbol() == Symbol() && OrderMagicNumber() == magic && OrderType() == tOper) {
         ticket = OrderTicket();
         if (ticket > oldTicket) {
            OPrice = OrderOpenPrice();
//            oldOrderPrice = OrderPrice;
            oldTicket = ticket;
         }
      }
   }
   return (OPrice);
}

void GetAccountInfo() {
   string str1,str2,str3,str4,str5,str6;
   switch (TradingType){
     case  3: {
                str1="Use double destinations";
                str2="OPEN BUY TRADES :                     " + DoubleToStr(OrdersCountByMagic(xMagicNumber), 0);
                str3="\n";
                str4="OPEN SELL TRADES :                    " + DoubleToStr(OrdersCountByMagic(AdvMagicNumber), 0);
                str5="NEXT BUY LOT(S) :                     " + DoubleToStr(opLot[0], 2);
                str6="NEXT SELL LOT(S) :                     " + DoubleToStr(opLot[1], 2);
              } break;
     default: {
                str1="Use single destination";
                str2="OPEN TRADES :                         " + DoubleToStr(OrdersCountByMagic(xMagicNumber), 0);
                str3="";
                str4="";
                str5="NEXT LOT(S) :                            " + DoubleToStr(opLot[0], 2);
                str6="";
              }
   }
   Comment("" 
      + "\n" 
      + "\n" 
      + "\n" 
      + "EXPERT VERSION: 1.0" 
      + "\n" 
      + "====================================" 
      + "\n" 
      + "-----------------------------------------------------------------------------------" 
      + "\n" 
      + "AUTHENTICATION STATUS" 
      + "\n" 
      + "-----------------------------------------------------------------------------------" 
      + "\n" 
      + "STATUS MESSAGE:   " + stErr 
      + "\n" 
      + "-----------------------------------------------------------------------------------" 
      + "\n" 
      + "ACCOUNT INFORMATION" 
      + "\n" 
      + "-----------------------------------------------------------------------------------" 
      + "\n" 
      + "Account Name:                " + AccountName() 
      + "\n" 
      + "Account Number:             " + AccountNumber() 
      + "\n" 
      + "Account Type:                 " + sTraiding 
      + "\n" 
      + "Account Leverage:           1:" + DoubleToStr(AccountLeverage(), 0) 
      + "\n" 
      + "Account Balance:             " + DoubleToStr(AccountBalance(), 2) 
      + "\n" 
      + "Account Equity:               " + DoubleToStr(AccountEquity(), 2) 
      + "\n" 
      + "-----------------------------------------------------------------------------------" 
      + "\n" 
      + "TRADE INFORMATIONS " 
      + "\n" 
      + "------------------------------------------------------------------------------------" 
      + "\n" 
      + "SAFE EQUITY STOP OUT :        " + SafeEquityStr 
      + "\n" 
      + "SAFE EQUITY RISK % :             " + DoubleToStr(SafeEquityRisk, 2) 
      + "\n" 
      + str5 + str3 + str6 
      + "\n"
      + str1
      + "\n" 
      + str2 + str3 + str4 
      + "\n" 
      + "FLOATING P/L :                         " + DoubleToStr(AccountProfit(), 2) 
      + "\n" 
   + "====================================");
}

int OrdersCountByMagic(int magic) {
   int total = OrdersTotal();
   int count = 0;
   for (int i = 0; i < total; i++) {
      OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
      if (OrderType() == OP_SELL || OrderType() == OP_BUY && OrderSymbol() == Symbol() && OrderMagicNumber() == magic) count++;
   }
   return (count);
}

string ReturnErrorMsg(int ai_0) {
   if (ai_0 == 0) return ("HTTP Error");
   if (ai_0 == 1) return ("Account does not exist or banned");
   if (ai_0 == 2) return ("Account Activation Successful");
   if (ai_0 == 3) return ("Account Authentication Successful");
   if (ai_0 == 4) return ("Account not Activated!!!");
   if (ai_0 == 5) return ("Insert a valid CLICKBANK ID.");
   return ("Ok");
}

bool func1(int a1, int a2, double a3, double a4, double a5, double a6, double a7, double a8, double a9)
{
   if ( a1 && a7 * a8 * a9 <= a5 - a4 ) return(true);
   if ( a2 && a3 - a6 >= a9 * a8 * a7 ) return(true);
   return(false);
}  

